### ISSUE TITLE
Compatible with SMW 4? Problems on installation

### ISSUE THREAD

**Issue by progtw** [SemanticMediaWiki/SemanticCite#113]
### Setup and configuration

- SMW version: 4.1
- SCI version: ?
- MW version: 39.2
- DB (MySQL etc. and version): MySQL

### Issue
When following the installation procedure, composer complains that SCI is not compatible with SMW 4.1 (only 3.x).
Is it actually compatible (Readme tells "[Semantic MediaWiki](https://github.com/SemanticMediaWiki/SemanticMediaWiki) 3.0 or later") and how then do I change the requirement to allow install without downgrading SMW?

```
composer update --no-dev
Could not scan for classes inside "extensions/SemanticMediaWiki//tests/phpunit/includes/" which does not appear to be a file nor a folder
> ComposerHookHandler::onPreUpdate
Loading composer repositories with package information
Info from https://repo.packagist.org: #StandWithUkraine
Updating dependencies
Your requirements could not be resolved to an installable set of packages.

  Problem 1
    - Root composer.json requires mediawiki/semantic-cite ~2.1 -> satisfiable by mediawiki/semantic-cite[2.1.0, 2.1.1].
    - mediawiki/semantic-cite[2.1.0, ..., 2.1.1] require mediawiki/semantic-media-wiki ~3.0 -> found mediawiki/semantic-media-wiki[3.0.0, ..., 3.2.3] but it conflicts with your root composer.json require (^4.1).

Use the option --with-all-dependencies (-W) to allow upgrades, downgrades and removals for packages currently locked to specific versions.
Running update with --no-dev does not mean require-dev is ignored, it just means the packages will not be installed. If dev requirements are blocking the update you have to resolve those problems.
```

**Comment by z929669** [comment]
You can use "mediawiki/semantic-cite": "dev-master" instead of "mediawiki/semantic-cite": "~2.1" in composer.json, but I'm getting errors with this extension in my nginx access log: 
`PHP Fatal error:  Uncaught Error: Undefined constant "CACHE_NONE" in /srv/sites/_wikidev/extensions/SemanticCite/DefaultSettings.php:45`
Using PHP 8.x

**Comment by krabina** [comment]
See #110

**Comment by kghbln** [comment]
#116

**Comment by tsadrafoundation** [comment]
I'm still seeing the issue installing dev-master with composer. I manually change `CACHE_EVERYTHING` to `-1` in `/var/www/html/extensions/SemanticCite/DefaultSettings.php` to make it work

SMW 4.1, MW 1.39, PHP 8.1
