### ISSUE TITLE
Make new release

### ISSUE THREAD

**Issue by JeroenDeDauw** [SemanticMediaWiki/SemanticCite#118]
* Update https://github.com/SemanticMediaWiki/SemanticCite/blob/master/RELEASE-NOTES.md
* Figure out next version number, as per SemVer. Perhaps following https://github.com/SemanticMediaWiki/SemanticMediaWiki/blob/master/docs/RELEASE-POLICY.md
* Update version in https://github.com/SemanticMediaWiki/SemanticCite/blob/master/extension.json
* once the above is merged, tag the new version and push the tag

**Comment by kizule** [comment]
I'm preparing PR for this, give me a moment.

**Comment by kghbln** [comment]
@JeroenDeDauw @krabina We still need a tag. Should I do it?

**Comment by kizule** [comment]
Ping 😄@kghbln

**Comment by kghbln** [comment]
Done. I forgot that I asked.
