### ISSUE TITLE
Issues with HookRegistry

### ISSUE THREAD

**Issue by kghbln** [SemanticMediaWiki/SemanticCite#15]
I am just setting up the [sandbox](https://github.com/SemanticMediaWiki/SemanticMediaWiki/issues/729) but fail to create the table during the `update.php` run:

```text
PHP Warning:  Missing argument 1 for SCI\HookRegistry::SCI\{closure}() in /.../w/extensions/SemanticCite/src/HookRegistry.php on line 121
PHP Notice:  Undefined variable: dataTypeRegistry in /.../w/extensions/SemanticCite/src/HookRegistry.php on line 123
PHP Fatal error:  Call to a member function registerDatatype() on a non-object in /.../w/extensions/SemanticCite/src/HookRegistry.php on line 123
```
*Setup:*
* MW 1.25.2, SMW 2.2.2, PHP 5.4.45, MariaDB 5.5.45

**Comment by mwjames** [comment]
> MW 1.25.2, SMW 2.2.2, PHP 5.4.45, MariaDB 5.5.45

SCI requires 2.3 (as stated) which is also the reason why 1.0 hasn't been released yet because it requires changes from the 2.3@dev master.

**Comment by kghbln** [comment]
Fair enough. Just copied the composer.local.json over from my test wiki which is running master.
