### ISSUE TITLE
Set up TWN mirror

### ISSUE THREAD

**Issue by JeroenDeDauw** [SemanticMediaWiki/SemanticCite#2]

**Comment by JeroenDeDauw** [comment]
Requested at https://www.mediawiki.org/wiki/Git/New_repositories/Requests

**Comment by JeroenDeDauw** [comment]
Mirror has been set up. https://github.com/wikimedia/mediawiki-extensions-SemanticCite

**Comment by mwjames** [comment]
:+1:

**Comment by kghbln** [comment]
Used to be an automatic process. Lately started to [manually ask for this](https://translatewiki.net/wiki/Thread:Support/Adding_support_for_Semantic_Cite_(SCI)).

**Comment by JeroenDeDauw** [comment]
Still not done :(

**Comment by kghbln** [comment]
I have just created [T106794](]https://phabricator.wikimedia.org/T106794?) for this. Sit tight.

**Comment by mwjames** [comment]
@kghbln  In light of his perseverance [0] we are honoured to crown him a 

![image](https://cloud.githubusercontent.com/assets/1245473/9775063/aa909914-574c-11e5-8760-44e95bf42c00.png)

[0] https://gerrit.wikimedia.org/r/#/c/237231/

**Comment by kghbln** [comment]
> perseverance

Is this similar to stamina ;) I am fattered.

**Comment by JeroenDeDauw** [comment]
First updates merged now \o/ 6ac90876d4a269814e0d4b7dd6667db6b553597c
