### ISSUE TITLE
1.0 release

### ISSUE THREAD

**Issue by kghbln** [SemanticMediaWiki/SemanticCite#20]
Are we cool for this? Now that SMW 2.3 is out, this extension cannot probably wait to do a world of good. :)

**Comment by JeroenDeDauw** [comment]
Just merged in some more translations

    23 files changed, 184 insertions(+), 29 deletions(-)

**Comment by mwjames** [comment]
I hope to see this happen over the coming weekend but currently I'd like to finish up the "case-insensitive regex " PR with me being still in the middle of some experiments before `onoi/tesa` can be unleashed.

**Comment by kghbln** [comment]
:+1: Many thanks!

**Comment by mwjames** [comment]
https://github.com/SemanticMediaWiki/SemanticCite/releases/tag/1.0.0

![image](https://cloud.githubusercontent.com/assets/1245473/11459142/f21ad43a-96cf-11e5-800b-0d41b3f201f3.png)

**Comment by kghbln** [comment]
Cool :+1:

**Comment by kghbln** [comment]
Jeroen has done the release tweet.
