### ISSUE TITLE
PHP Fatal error:  Access level to SCI\DataValues\ResourceIdentifierStringValue::getPreferredCaption() must be public

### ISSUE THREAD

**Issue by kghbln** [SemanticMediaWiki/SemanticCite#30]
### Setup and configuration

- PHP 	5.6.11-1ubuntu3.4 (apache2handler)
- MySQL 	5.6.30-0ubuntu0.15.10.1
- MediaWiki 	1.25.6 (01b4001) 21:49, 20 May 2016
- Semantic MediaWiki	2.4.0 (61b7da6) 06:23, 9 July 2016
- Semantic Cite	1.0.0 (68c619e) 22:03, 29 November 2015

### Issue
When running "rebuildData.php" on smw.o the following fatal occurs twice:
```
PHP Fatal error:  Access level to SCI\DataValues\ResourceIdentifierStringValue::getPreferredCaption() must be public (as in class SMWDataValue) in /.../w/extensions/SemanticCite/src/DataValues/ResourceIdentifierStringValue.php on line 124
```
Affected page:
- [Help:Data_import_with_a_script with](https://www.semantic-mediawiki.org/wiki/Help:Data_import_with_a_script) (ID 10 and 311)

**Comment by mwjames** [comment]
Has been fixed a while ago with https://github.com/SemanticMediaWiki/SemanticCite/pull/26, just need to make a release.

**Comment by mwjames** [comment]
https://github.com/SemanticMediaWiki/SemanticCite/releases/tag/1.1.0

**Comment by kghbln** [comment]
Well, sometimes it is advantageous to look what has already been reported. Still had "rebuildData.php" nightmare, so more reports to come.

Just updated the wiki to SCI 1.1.0.
