### ISSUE TITLE
Wrapping citation text instead of splitting

### ISSUE THREAD

**Issue by kghbln** [SemanticMediaWiki/SemanticCite#32]
### Setup and configuration

- MediaWiki 	1.25.6 (01b4001) 21:49, 20 May 2016
- PHP 	5.6.11-1ubuntu3.4 (apache2handler)
- MySQL 	5.6.31-0ubuntu0.15.10.1
- Semantic Cite	1.1.1 (a98b566) 18:33, 9 July 2016

### Issue
It will be nice if the citation resource description gets wrapped within the respective column rather than split to several columns. See the screen shot from [Help:RebuildFulltextSearchTable.php](https://www.semantic-mediawiki.org/wiki/Help:RebuildFulltextSearchTable.php):

![bildschirmfoto vom 2016-08-12 14 41 27](https://cloud.githubusercontent.com/assets/1104078/17622472/e874bd34-609a-11e6-9e8a-0a9e4a247ffb.png)

**Comment by mwjames** [comment]
> It will be nice if the citation resource description gets wrapped within the respective column rather than split to several columns. See the screen shot from Help:RebuildFulltextSearchTable.php:

By default the "auto" reference list uses a cheap heuristic to determine whether to use a responsive column or to switch to [0] `scite-referencelist-columns-responsive-single` when the content length is insufficient (< length 300).

[0] https://github.com/SemanticMediaWiki/SemanticCite/blob/master/src/ReferenceListOutputRenderer.php#L252-L254

**Comment by mwjames** [comment]
Expected to be addressed with #35.

**Comment by kghbln** [comment]
Indeed, that fixed it. Thanks a lot and sorry for not responding for such a long time.
