### ISSUE TITLE
References header and references are sometimes detatched

### ISSUE THREAD

**Issue by kghbln** [SemanticMediaWiki/SemanticCite#33]
### Setup and configuration

- MediaWiki 	1.25.6 (01b4001) 21:49, 20 May 2016
- PHP 	5.6.11-1ubuntu3.4 (apache2handler)
- MySQL 	5.6.31-0ubuntu0.15.10.1
- Semantic Cite	1.1.1 (a98b566) 18:33, 9 July 2016

### Issue
Sometimes the References header and the references appear detached if another element causes a gap between the end of the text and the footer. See the screen shot from [Help:Property usage count](https://www.semantic-mediawiki.org/wiki/Help:Property_usage_count):

![bildschirmfoto vom 2016-08-13 23 32 11](https://cloud.githubusercontent.com/assets/1104078/17645791/edd7118a-61af-11e6-95e1-88aa0fe929be.png)

**Comment by kghbln** [comment]
This only happens when you have more than one column. See [this page](https://www.semantic-mediawiki.org/wiki/Help:$smwgEnabledEditPageHelp) for a one column example.

**Comment by mwjames** [comment]
Expected to be addressed with #35. Would be great if you can confirm this and if you have to time push it as 1.1.2 release.

**Comment by kghbln** [comment]
> Would be great if you can confirm this and if you have to time push it as 1.1.2 release.

Again sorry for having kept you waiting so long. Affirmative this issue is fixed. However I have applied a tiny tweak together with the release pull https://github.com/SemanticMediaWiki/SemanticCite/pull/37 to mitigate the issue see at the bottom of [this page](https://www.semantic-mediawiki.org/wiki/Help:Property_usage_count) Note the wiki is currently on SCI master.

**Comment by mwjames** [comment]
> However I have applied a tiny tweak together with the release pull #37 to mitigate the issue

... and that's why it is called open-source!
