### ISSUE TITLE
instructions for installing without composer

### ISSUE THREAD

**Issue by the1gofer** [SemanticMediaWiki/SemanticCite#34]
Are there any instructions for installing without composer?

**Comment by mwjames** [comment]
> Are there any instructions for installing without composer?

No, and to be honest I'm not prepared to spend time on making an extra tarball release. @kghbln Do we have somewhere a verbatim (non-Scite specific) instruction on how to install and copy a local Composer install?

**Comment by the1gofer** [comment]
Just tell me what files need to be uploaded, and the command for the config file.

**Comment by kghbln** [comment]
We are talking about an [individual file release](https://www.semantic-mediawiki.org/w/index.php?title=Help:Using_Composer&redirect=no#Individual_file_release) here. You will have to extend the linked example "composer.json" file by `"mediawiki/semantic-cite": "~1.1"`.

**Comment by the1gofer** [comment]
I got the files manually downloaded, their is no command for LocalSetting.php, such asrequire_once "$IP/extensions/SemanticCite/SemanticCIte.php"  ... or something.

**Comment by mwjames** [comment]
> I got the files manually downloaded, their is no command for LocalSetting.php, such asrequire_once "$IP/extensions/SemanticCite/SemanticCIte.php" ... or something.

This is not going to work and to avoid me writing the same thing twice as to why, please have a look at [0].

[0] https://github.com/JeroenDeDauw/Maps/issues/216#issuecomment-241374111

**Comment by the1gofer** [comment]
Wow, I'm sorry. Great community you have here.

**Comment by mwjames** [comment]
> Great community you have here.

Not sure I interpret this as honest or sarcastic comment but to clarify I'll provide support in may free time, if people need or require something the are welcome to contribute after all this is free software. Personally, I'm under no obligation to make an effort that goes beyond my personal investment or requirement.
