### ISSUE TITLE
Problem with Find citable metadata

### ISSUE THREAD

**Issue by andbue** [SemanticMediaWiki/SemanticCite#42]
### Setup and configuration

- SMW version: 2.5.1
- SCI version: 1.2.0
- MW version: 1.28.1
- DB (MySQL etc.): SQLite

### Issue

Using the "Find citable metadata"-Page works for me only in "Raw" mode. Searching for any DOI or other identifier results in a blank page.
The PHP error I get is "Fatal error: Call to a member function getValueFormatter() on null in /var/www/mediawiki/extensions/SemanticMediaWiki/includes/datavalues/SMW_DV_String.php on line 111".

Any idea what could be the problem?

Thanks!

**Comment by mwjames** [comment]
Hi,

> Searching for any DOI or other identifier results in a blank page.
> The PHP error I get is "Fatal error: Call to a member function
> getValueFormatter() on null in

This has been fixed back in November on the master branch but as of
now we haven't released any new version.

PS: @kghbln in case we want to do a release then `composer.json` needs
to be adjusted with:

Remove `|~3.0` for the release

* "mediawiki/semantic-media-wiki": "~2.3",

and re-add it after the release to ensure ~3.0 isn't part of the boundary yet.

Cheers

**Comment by kghbln** [comment]
This should be a SCI 1.3.0 due to https://github.com/SemanticMediaWiki/SemanticCite/pull/38 which breaks with SMW 2.3.x. New minimum requirement is SMW 2.5.x if I am not mistaken?!

**Comment by kghbln** [comment]
It will be SCI 1.3.0 anyways since https://github.com/SemanticMediaWiki/SemanticCite/commit/2c5a153cfb84d57d972eaeae5e8ffdbb05b84cb6 requires PHP 5.5+. To avoid breakage with SMW 2.3 I could however tag this version alternatively.

@mwjames A short hint which way you prefer will be cool

**Comment by mwjames** [comment]
> A short hint which way you prefer will be cool

If you want to make a quick 1.3 without the 5.5 requirement then this is fine. The related fixes are done before the cut and include fd76a08 and 008097d. 

Again, I have no strong preference.

**Comment by kghbln** [comment]
> Again, I have no strong preference.

Ok, will do a 1.2.1 with the tag at https://github.com/SemanticMediaWiki/SemanticCite/commit/008097d0eb8e928481c6e453295dba3aa64833de

Compat breaking 1.3.0 can be done next week or so.

**Comment by kghbln** [comment]
Ah this is getting to complicated. 1.3.0 for master and if somebody complains he or she could get an unofficial 1.2.1 tag. ;)

**Comment by kghbln** [comment]
This was not a good week for me, however finally [SCI 1.3.0](https://github.com/SemanticMediaWiki/SemanticCite/releases/tag/1.3.0) is out. Thanks for sitting tight!
