### ISSUE TITLE
HHVM: Fatal error: Uncaught exception 'InvalidArgumentException'

### ISSUE THREAD

**Issue by kghbln** [SemanticMediaWiki/SemanticCite#43]
### Setup and configuration

- SMW version: master
- SCI version: master
- MW version: 1.26.3
- PHP version: HHVM
- DB (MySQL etc.): MySQl

### Issue

[Build job fails](https://travis-ci.org/SemanticMediaWiki/SemanticCite/jobs/227160754) with ...

Fatal error: Uncaught exception 'InvalidArgumentException' with message 'The value for 'load_composer_autoloader' should be an array' in /home/travis/build/SemanticMediaWiki/mw/includes/registration/ExtensionProcessor.php:348

### Stack trace

```
#0 /home/travis/build/SemanticMediaWiki/mw/includes/registration/ExtensionProcessor.php(173): ExtensionProcessor->storeToArray()
#1 /home/travis/build/SemanticMediaWiki/mw/includes/registration/ExtensionRegistry.php(202): ExtensionProcessor->extractInfo()
#2 /home/travis/build/SemanticMediaWiki/mw/includes/registration/ExtensionRegistry.php(127): ExtensionRegistry->readFromQueue()
#3 /home/travis/build/SemanticMediaWiki/mw/includes/Setup.php(39): ExtensionRegistry->loadFromQueue()
#4 /home/travis/build/SemanticMediaWiki/mw/maintenance/doMaintenance.php(97): include()
#5 /home/travis/build/SemanticMediaWiki/mw/maintenance/update.php(214): include()
#6 {main}
```

**Comment by mwjames** [comment]
> mw/includes/registration/ExtensionProcessor.php(173): ExtensionProcessor->storeToArray()

The is a pure MediaWiki thing, https://phabricator.wikimedia.org/T135870. We are not using any `extension.json` so I'm not sure why this pops up.

**Comment by kghbln** [comment]
> The is a pure MediaWiki thing, https://phabricator.wikimedia.org/T135870. We are not using any extension.json so I'm not sure why this pops up.

So unless the fix is not being backported to REL1_27 HHVM is not an option for SCI?

**Comment by kghbln** [comment]
> We are not using any extension.json so I'm not sure why this pops up.

Oh man now I understand the extend of this issue.

**Comment by mwjames** [comment]
> So unless the fix is not being backported to REL1_27 HHVM is not an option for SCI?

I'm too tired with these guess, so I just changed the required MW release on Travis [0]. Someone changed something, somewhere but don't ask any details!

[0] https://github.com/SemanticMediaWiki/SemanticCite/commit/0eb133d2b67246eba74e9236a241711463fc798e

**Comment by kghbln** [comment]
> I'm too tired with these guys, so I just changed the required MW release on Travis [0]. Someone changed something, somewhere but don't ask any details!

Well 1.26.x is no longer supported anyways. Let's move on ...
