### ISSUE TITLE
Input field label on "Special:FindCitableMetadata" should be localizable

### ISSUE THREAD

**Issue by kghbln** [SemanticMediaWiki/SemanticCite#45]
### Setup and configuration

- SCI version: master

### Issue
The [input field label](https://github.com/SemanticMediaWiki/SemanticCite/blob/master/src/Specials/CitableMetadata/PageBuilder.php#L138) on special page "FindCitableMetadata" should be localizable and probably be called "Source" instead of "Type"

Steps to reproduce the observation (recommendation is to use the [sandbox](http://sandbox.semantic-mediawiki.org)):

See [here](https://sandbox.semantic-mediawiki.org/wiki/Sp%C3%A9cial:FindCitableMetadata?uselang=qqx).

**Comment by mwjames** [comment]
> The input field label on special page "FindCitableMetadata" should be localizable and probably be called "Source" instead of "Type"

Well, currently this is hard-coded https://github.com/SemanticMediaWiki/SemanticCite/blob/master/src/Specials/CitableMetadata/PageBuilder.php#L139.

**Comment by kghbln** [comment]
> Well, currently this is hard-coded https://github.com/SemanticMediaWiki/SemanticCite/blob/master/src/Specials/CitableMetadata/PageBuilder.php#L139.

Probably `addOptionSelectList()`just needs to be an array togehter with replacing "Type:" by `$messageBuilder->getMessage( 'sci-metadata-search-type-label' )->text()`?

**Comment by mwjames** [comment]
> Probably addOptionSelectList()just needs to be an array together with replacing "Type:" by 

Only `Type:` needs to replaced by something like `$messageBuilder->getMessage( 'sci-metadata-search-type-label' )->text()`.

**Comment by kghbln** [comment]
> Only Type: needs to replaced by something like $messageBuilder->getMessage( 'sci-metadata-search-type-label' )->text()

Ah ok, since the whole content is already treated as an array.
