### ISSUE TITLE
Search for PMID and PMCID forbidden

### ISSUE THREAD

**Issue by kghbln** [SemanticMediaWiki/SemanticCite#48]
### Setup and configuration

- MediaWiki 	1.28.1 (819c0d2) 00:51, 7 April 2017
- PHP 	5.6.30-0+deb8u1 (apache2handler)
- MariaDB 	10.0.30-MariaDB-1~jessie
- Semantic MediaWiki	3.0.0-alpha (63c9206) 08:48, 11 May 2017
- Semantic Cite	1.4.0-alpha (c0368d4) 08:48, 11 May 2017	GPL-2.0+

### Issue
A search via special page "FindCitableMetadata" returns:
```
The REST/HTTP request returned with "The requested URL returned error: 403 Forbidden" for "5348191".
````
Perhaps they have changed their API. The search for DOIs is working as expected.

Steps to reproduce the observation (recommendation is to use the [sandbox](http://sandbox.semantic-mediawiki.org)):
* [PMID 28272243](https://sandbox.semantic-mediawiki.org/w/index.php?title=Sp%C3%A9cial%3AFindCitableMetadata&type=pubmed&id=28272243)
* [PMCID PMC5348191](https://sandbox.semantic-mediawiki.org/w/index.php?title=Sp%C3%A9cial%3AFindCitableMetadata&type=pmc&id=PMC5348191)

**Comment by mwjames** [comment]
> The REST/HTTP request returned with "The requested URL returned error: 403 Forbidden" for "5348191".

The REST API turned from HTTP to HTTPS https://github.com/onoi/remi/commit/33b0d440dcea1896bd177266ff3988b2099dae00.

**Comment by mwjames** [comment]
On the event of a `composer update` you should get the new https://github.com/onoi/remi/releases/tag/0.4.0.

**Comment by kghbln** [comment]
Perfect. Issue solved as the field tests confirm. :)
