### ISSUE TITLE
Install without composer?

### ISSUE THREAD

**Issue by m-art-in** [SemanticMediaWiki/SemanticCite#49]
### Setup and configuration

- SMW version: 2.4.1
- MW version: 1.27.1
- DB: PostgresSQL

### Howto install without composer / shell access
I tried to install the extension without shell access. Download from git, datatransfern on my server via sftp and added the line `require_once("$IP/extensions/SemanticCite/SemanticCite.php");` to my LocalSettings.php but this doesn't work. Any suggestions?

Thanks!

**Comment by kghbln** [comment]
[This should probably say](https://github.com/SemanticMediaWiki/SemanticCite/blob/master/README.md#installation) The only way to install is using Composer.

You can do the installation on a machine allowing to use Composer and then move over the files to your environment.

**Comment by m-art-in** [comment]
> You can do the installation on a machine allowing to use Composer and then move over the files to your environment.

This is a good idea!, thanks @kghbln

**Comment by kghbln** [comment]
No worries. I do it like this from time to time too.
