### ISSUE TITLE
API error: badtoken

### ISSUE THREAD

**Issue by mwColin** [SemanticMediaWiki/SemanticCite#50]
### Setup and configuration

- SMW version: 2.5.2
- SCI version: 1.3.0
- MW version: 1.27.0
- DB (MySQL etc.): 10.0.29-MariaDB-0ubuntu0.16.04.1

### Issue
I get a "API error: badtoken" error when I click on the "create" button after I have obtained the reference using a search for a DOI.

Semantic cite was working correctly before an upgrade of SMW from 2.4 to 2.5. Semantic cite was also upgraded. 

Any ideas on the cause?

Thanks,
Colin

**Comment by mwColin** [comment]
I have found the issue. My database was in read-only mode due to a backup taking place.

So... if you get this error, check that your database is not in read-only mode!

**Comment by kghbln** [comment]
Great that you found the cause.
