### ISSUE TITLE
No templates availabe on page MediaWiki:Sci-template-definition

### ISSUE THREAD

**Issue by kernie** [SemanticMediaWiki/SemanticCite#61]
### Setup and configuration

- SMW version: 2.5.5
- SCI version: 1.3.0
- MW version: 1.27.4
- DB (MySQL etc.): MySQL 5.7.22

### Issue

After installation the page MediaWiki:Sci-template-definition does not contain the template entries as described in https://github.com/SemanticMediaWiki/SemanticCite/blob/master/docs/10-template-examples.md .

A passage such as 
{{#scite:Byrne 2008
 |type=journal
 |author=Byrne, A
 |year=2008
 |title=Web 2.0 strategies in libraries and information services
 |journal=The Australian Library Journal
 |volume=57
 |number=4
 |pages=365-376
}}
leads to an error: "#scite could not render a citation text for reference "Byrne 2008" because type "journal" was not assigned to a template."

Any idea?

Thank you for your help!
Maarten

**Comment by kghbln** [comment]
Did you add a type-template pair to "MediaWiki:Sci-template-definition" such as `journal|SciteMLACitationFormatter` as done [here](https://sandbox.semantic-mediawiki.org/wiki/MediaWiki:Sci-template-definition)? Moreover you should not forget to create the respective template, too as done [there](https://sandbox.semantic-mediawiki.org/wiki/Mod%C3%A8le:SciteMLACitationFormatter).

**Comment by kernie** [comment]
So it seems that simply my installation should have included the creation/edit of the of the Wiki pages as suggested where I thought that some general templates and definitions should have been there... Understood.

Now I tried to change the MediaWiki:Sci-template-definition page, but it is set to be read-only? Is there a namespace protection or so by default in place?

Thanks,
Maarten

**Comment by kghbln** [comment]
> So it seems that simply my installation should have included ...

Right.

> Now I tried to change the MediaWiki:Sci-template-definition page, but it is set to be read-only? Is there a namespace protection or so by default in place?

Indeed, you require the "editinterface" permission which is by default assigned to the "admin" user group.

**Comment by kernie** [comment]
Thank you!
So problem solved...
