### ISSUE TITLE
tooltip does not show up

### ISSUE THREAD

**Issue by bescheid** [SemanticMediaWiki/SemanticCite#86]
### Setup and configuration

- SMW version:3.1.6
- SCI version:2.1.0
- MW version:1.31.1
- DB (MySQL etc. and version):10.1.40-MariaDB

### Issue

Hovering over cite-numbers only produces a loading symbol.

The browser console produces a [stack trace](https://www.semantic-mediawiki.org/wiki/Help:Identifying_bugs) and outputs:

`VM3336:230 Uncaught TypeError: api.parse is not a function`

The error seems to have been discussed at #70, but no solution has been presented.

Steps to reproduce the observation (recommendation is to use the [sandbox](https://sandbox.semantic-mediawiki.org)):

https://www.univie.ac.at/rel_jap/an/Sandkiste2/SCI_example

**Comment by kghbln** [comment]
> The error seems to have been discussed at #70, but no solution has been presented.

I believe @JeroenDeDauw suggested to downgrade SCI. Change the line in your "composer.local.json" file to "mediawiki/semantic-cite": "~2.0.0" and see what happens.

**Comment by kghbln** [comment]
@mwjames I just looked at the commits and saw the unreleased pull which slipped my attention: https://github.com/SemanticMediaWiki/SemanticCite/pull/71 Actually doing a SCI 2.1.1 release will be another way to resolve this?!

**Comment by bescheid** [comment]
> I believe @JeroenDeDauw suggested to downgrade SCI. Change the line in your "composer.local.json" file to "mediawiki/semantic-cite": "~2.0.0" and see what happens.

Thank you for clarifying Jeroen's cryptic suggestion, I will try...

**Comment by bescheid** [comment]
> Change the line in your "composer.local.json" file to "mediawiki/semantic-cite": "~2.0.0" and see what happens.

This crushed my system. Had to re-upgrade SCI to 2.1 to keep the site running...

**Comment by kghbln** [comment]
> This crushed my system. Had to re-upgrade SCI to 2.1 to keep the site running...

I am a bit surprised but yeah, perhaps a new release is the best way.

**Comment by bescheid** [comment]
This seems to pass the task over to @mwjames. Many thanks in advance for your efforts. For the time being, I will stay with extension:cite and/or disable SCI tooltips by CSS. I leave this issue open, however...

**Comment by mwjames** [comment]
> This seems to pass the task over to @mwjames. Many thanks in advance for
> your efforts. For the time being, I will stay with extension:cite and/or
> disable SCI tooltips by CSS. I leave this issue open, however...

I don't know what and why you have an issue here but #71 is in place
to account for the cluster.... produced by the WMF. Anyway as far as I
remember [0] uses MW 1.31 and SCI 2.1 and it works.

[0] https://www.semantic-mediawiki.org/wiki/Help:Import_vocabulary

**Comment by mwjames** [comment]
> I don't know what and why you have an issue here but #71 is in place

See also [0].

[0] https://github.com/SemanticMediaWiki/SemanticCite/commit/186e1698dea4bf8a531e50aaf4214f241126b9f5

**Comment by kghbln** [comment]
@mwjames So doing a release as suggested in https://github.com/SemanticMediaWiki/SemanticCite/issues/86#issuecomment-628106831 will help regain paradise?

**Comment by mwjames** [comment]
> @mwjames So doing a release as suggested in
> https://github.com/SemanticMediaWiki/SemanticCite/issues/86#issuecomment-628106831
> will help regain paradise?

Honestly I don't know because the current SCI 2.1.0 and MW 1.31 does
work as outlined above.

**Comment by bescheid** [comment]
https://github.com/SemanticMediaWiki/SemanticCite/commit/186e1698dea4bf8a531e50aaf4214f241126b9f5 solved my problems (sorry for not finding it earlier). I added the lines suggested by @mwjames to semanticCite.php. Thk you for your efforts!

**Comment by kghbln** [comment]
> Honestly I don't know because the current SCI 2.1.0 and MW 1.31 does work as outlined above.

It may be that I manually modified the code for it to work. I faintly remember. I will uninstall and install to get the canonical code..

**Comment by mwjames** [comment]
> 186e169 solved my problems (sorry for not finding it earlier).

But those lines should be part of a release???

**Comment by bescheid** [comment]
Not my release (2.1.0), that's for sure.

**Comment by kghbln** [comment]
> Not my release (2.1.0), that's for sure.

That's not was meant by the question. Anyhow this issue is a dupe in the end.

@mwjames I indeed manually changed the code since this is what composer gives me:
```
Loading composer repositories with package information
Updating dependencies
Package operations: 0 installs, 0 updates, 2 removals
  - Removing onoi/remi (0.4.0)
  - Removing mediawiki/semantic-cite (2.1.0)
    The package has modified files:
    M SemanticCite.php
    Discard changes [y,n,v,d,?]? 
```
I verified that the issue in present for MW 1.31 and SCI 2.1.0 on a totally different wiki and only after updating SCI to master the issue is gone, i.e. I will do a SCI 2.1.1 release tomorrow.

**Comment by mwjames** [comment]
> @mwjames I indeed manually changed the code since this is what composer
> gives me:

Which explains the false assumption.

> I will do a SCI 2.1.1 release tomorrow.

Whenever it fits your calendar.
