### ISSUE TITLE
Uncaught ReferenceError: onoi is not defined

### ISSUE THREAD

**Issue by kghbln** [SemanticMediaWiki/SemanticCite#98]
### Setup and configuration

- MediaWiki | 1.35.0-rc.2 (0f1a2a2)18:43, 21 August 2020
- PHP | 7.2.24-0ubuntu0.18.04.6 (apache2handler)
- MariaDB | 10.1.44-MariaDB-0ubuntu0.18.04.1
- Semantic Cite | 2.1.1 (01dc68a) 12:04, 16 May 2020

### Issue
```
Uncaught ReferenceError: onoi is not defined
    <anonymous> https://sandbox.semantic-mediawiki.org/w/extensions/SemanticCite/res/scite.tooltip.js?ecade:153
scite.tooltip.js:153:1
```

Steps to reproduce the observation (recommendation is to use the [sandbox](https://sandbox.semantic-mediawiki.org)):

https://sandbox.semantic-mediawiki.org/wiki/20200823?debug=true

**Comment by krabina** [comment]
I can confirm this. Exact same error appearing in 

Semantic Cite | 2.1.1 (01dc68a) 11:04, 16 May 2020
Semantic MediaWiki | 3.2.2
MediaWiki | 1.31.12
PHP | 7.3.23 (fpm-fcgi)
MariaDB | 10.3.25-MariaDB
ICU | 50.2

**Comment by TSchroth** [comment]
I have the following issue related to onoi when trying to use Special:FindCitableMetadata, is this the same problem?


MediaWiki 1.35.5
PHP 7.4.27 (apache2handler)
MySQL 5.7.36-0ubuntu0.18.04.1
SMW 3.2.3
SSC 2.1.1
Via Semantic Bundle 5

```
[85208130992782b3e34b5f1b] /index.php/Special:FindCitableMetadata Error from line 62 of /var/www/wikifolder/vendor/onoi/http-request/src/HttpRequestFactory.php: Call to undefined function Onoi\HttpRequest\curl_init()

Backtrace:

#0 /var/www/wikifolder/extensions/SemanticCite/src/Specials/SpecialFindCitableMetadata.php(122): Onoi\HttpRequest\HttpRequestFactory->newCachedCurlRequest()
#1 /var/www/wikifolder/extensions/SemanticCite/src/Specials/SpecialFindCitableMetadata.php(69): SCI\Specials\SpecialFindCitableMetadata->newPageBuilder()
#2 /var/www/wikifolder/extensions/SemanticCite/src/Specials/SpecialFindCitableMetadata.php(64): SCI\Specials\SpecialFindCitableMetadata->callPageBuilderFor()
#3 /var/www/wikifolder/includes/specialpage/SpecialPage.php(600): SCI\Specials\SpecialFindCitableMetadata->execute()
#4 /var/www/wikifolder/includes/specialpage/SpecialPageFactory.php(635): SpecialPage->run()
#5 /var/www/wikifolder/includes/MediaWiki.php(307): MediaWiki\SpecialPage\SpecialPageFactory->executePath()
#6 /var/www/wikifolder/includes/MediaWiki.php(945): MediaWiki->performRequest()
#7 /var/www/wikifolder/includes/MediaWiki.php(548): MediaWiki->main()
#8 /var/www/wikifolder/index.php(53): MediaWiki->run()
#9 /var/www/wikifolder/index.php(46): wfIndexMain()
#10 {main}
```

Can I do sth. to fix this in my installation?

**Comment by krabina** [comment]
I suppose this is fixed in V3.
